import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/ui/mode";
import { Providers } from "./RTK/Provider";
import Sidebar from "./component/Sidebar";
import RestrictSidebar from "./RestrictSideBar/page";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* <ThemeProvider> */}
            <RestrictSidebar>
              <div>

                <main >{children}</main>
              </div></RestrictSidebar>
          {/* </ThemeProvider> */}
        </Providers></body>
    </html>
  );
}
